[package]
name = "pwn"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.7.0"

[dependencies]
starknet = "2.7.0"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
openzeppelin_account = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true

[tool.fmt]
sort-module-level-items = true

[tool.snforge]
exit-first = true

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"
block_id.tag = "Latest"
