# .github/workflows/handle-prs.yml

name: Handle PRs

on:
  pull_request_target:
    branches:
      - main

jobs:
  handle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: '2.6.5'

      - name: Run Format Check
        run: scarb fmt --check

      - name: Run Build
        run: scarb build

      - name: Set up Snfoundry
        uses: foundry-rs/setup-snfoundry@v3

      - name: Run Tests
        run: snforge test

      - name: Checkout Staging Branch
        if: success()
        uses: actions/checkout@v4
        with:
          ref: pr-pre-merge-target

      - name: Merge PR to Staging
        if: success()
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "merge-bot"
          git merge ${{ github.event.pull_request.head.ref }}
          git push origin pr-pre-merge-target
